In [253]:
#age decode
age_map = {1: '0 - 1',
2: '1 - 4 years',
3: '5 - 14 years',
4: '15 - 24 years',
5: '25 - 34 years',
6: '35 - 44 years',
7: '45 - 54 years',
8: '55 - 64 years',
9: '65 - 74 years',
10: '75 - 84 years',
11: '85 years and older',
12: 'Age not stated'}

In [254]:
#fixed width file locations adjusted for index 
data_map = {2023: {'icd': (145, 149),'icd_recode': (149,152), 'age': (78, 80), 'race':(449,450), 'race_12': (486,488), 'sex':(68,69), 'location':(144,145), 'marital':(83,84), 'activity':(143,144),'education':(62,63), 'co-morb_1':(343,348), 'co-morb_2':(348,353), 'co-morb_3':(353,358), 'co-morb_4':(358,363), 'co-morb_5':(363,368), 'co-morb_6':(368,373), 'co-morb_7':(373,378), 'co-morb_8':(378,383), 'co-morb_9':(383,388), 'co-morb_10':(388,393), 'co-morb_11':(393,398), 'co-morb_12':(398,403), 'co-morb_13':(403,408), 'co-morb_14':(408,413), 'co-morb_15':(413,418), 'co-morb_16':(418,423), 'co-morb_17':(423,428), 'co-morb_18':(428,433), 'co-morb_19':(433,438), 'co-morb_20':(438,443)},
           
           }

In [255]:
#location decode
location_map = {
    0: 'Home',
1: 'Residential institution',
2: 'School, other institution and public administrative area',
3: 'Sports and athletics area',
4: 'Street and highway',
5: 'Trade and service area',
6: 'Industrial and construction area',
7: 'Farm',
8: 'Other Specified Places',
9: 'Unspecified place',}

In [256]:
# sex decode
sex_map = {'M': 'male',
           'F': 'female'}

In [257]:
# icd 10 codes for drowning and translation
icd_10_drowning_codes = {
    "W65": "Accidental drowning and submersion while in bathtub",
    "W66": "Accidental drowning and submersion following fall into bathtub",
    "W67": "Accidental drowning and submersion while in swimming pool",
    "W68": "Accidental drowning and submersion following fall into swimming pool",
    "W69": "Accidental drowning and submersion while in natural water",
    "W70": "Accidental drowning and submersion following fall into natural water",
    "W73": "Other specified accidental drowning and submersion",
    "W74": "Unspecified accidental drowning and submersion",
    "V90": "Drowning and submersion due to accident to watercraft",
    "V92": "Drowning and submersion due to accident on board watercraft without accident to watercraft"}

In [258]:
#education decode
education_map = { 1:'8th grade or less',
2:'9 - 12th grade, no diploma',
3:'high school graduate or GED completed',
4:'some college credit, but no degree',
5:'Associate degree',
6:'Bachelor’s degree',
7:'Master’s degree',
8:'Doctorate or professional degree',
9:'Unknown' 
}

In [259]:
# marital status decode
marital_map = {'S':'Never married, single',
'M':'Married',
'W':'Widowed',
'D':'Divorced',
'U':'Marital Status unknown'   
}

In [260]:
#activity decode
activity_map = {0:'While engaged in sports activity',
1:'While engaged in leisure activity',
2:'While working for income',
3:'While engaged in other types of work',
4:'While resting, sleeping, eating (vital activities)',
8:'While engaged in other specified activities',
9:'During unspecified activity',   
}

In [261]:
# race recode 6 decode
race_map = {1: 'White',
 2:'Black',
 3: 'American Indian and Alaska Native',
 4: 'Asian',
 5: 'Native Hawaiian or Other Pacific Islander',
 6: 'multiracial'}

In [262]:
# race recode 12 decode
race_map_12 = {1: 'Mexican',
2:'Puerto Rico',
3:'Cuban',
4:'Dominican',
5:'Central American',
6:'South American',
7:'Other or Unknown Hispanic',
8:'Non-Hispanic White (only)',
9:'Non-Hispanic Black (only)',
10:'Non-Hispanic American Indian and Alaska Native (only)',
11:'Non-Hispanic Asian (only)',
12:'Non-Hispanic Native Hawaiian or Other Pacific Islander (only)',
13:'Non-Hispanic more than one race',
14:'Hispanic origin unknown or not stated'}

In [263]:
#custom map for use in replace, combines all my decode dicts
map_2023 = {'icd':icd_10_drowning_codes, 'age': age_map, 'race': race_map, 'race_12':race_map_12, 'sex': sex_map, 'location':location_map, 'activity':activity_map, 'marital':marital_map, 'education':education_map}

In [264]:
import pandas as pd

In [265]:
#this is the big extract block
# reads fixed width file, pull coded data from specific locations 
#File name was edited from the zip file for readability, link in read me
universal_set = pd.read_fwf('2023 mortality.fwf', colspecs = [*data_map[2023].values()], header=None, names=[*data_map[2023].keys()])
# preserving 4 digit icd code, for future analysis 
universal_set['icd_raw'] = universal_set['icd']
# slicing to 3 digit icd code
universal_set['icd'] = universal_set['icd'].str[:3]
# adding a year column for future analysis
universal_set['year'] = 2023
# filtering down to only drowning deaths via the trimmed icd code
drowning_test = universal_set[universal_set['icd'].isin(icd_10_drowning_codes.keys())]
# replacing coded values with the decode from my maps
drowning_test = drowning_test.replace(map_2023)
# sneak peak at my data to make sure decode was sucessful
drowning_test.head(20)

,icd,icd_recode,age,race,race_12,sex,location,marital,activity,education,...,co-morb_13,co-morb_14,co-morb_15,co-morb_16,co-morb_17,co-morb_18,co-morb_19,co-morb_20,icd_raw,year
623,Accidental drowning and submersion following f...,409,35 - 44 years,White,Non-Hispanic White (only),male,Other Specified Places,"Never married, single",During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W70,2023
1022,Accidental drowning and submersion while in ba...,409,35 - 44 years,White,Non-Hispanic White (only),female,Trade and service area,"Never married, single",During unspecified activity,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W65,2023
1030,Accidental drowning and submersion while in ba...,409,55 - 64 years,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,female,Home,Married,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W65,2023
1202,Accidental drowning and submersion following f...,409,35 - 44 years,White,Non-Hispanic White (only),male,Other Specified Places,"Never married, single",During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W70,2023
1420,Drowning and submersion due to accident on boa...,400,65 - 74 years,White,Non-Hispanic White (only),male,Other Specified Places,Divorced,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V929,2023
1443,Accidental drowning and submersion while in na...,409,65 - 74 years,White,Non-Hispanic White (only),male,Other Specified Places,Divorced,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W69,2023
1527,Accidental drowning and submersion while in na...,409,35 - 44 years,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,male,Other Specified Places,Married,During unspecified activity,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W69,2023
1791,Unspecified accidental drowning and submersion,409,15 - 24 years,White,Puerto Rico,male,Other Specified Places,Married,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W74,2023
1879,Accidental drowning and submersion while in na...,409,15 - 24 years,White,Non-Hispanic White (only),male,Other Specified Places,"Never married, single",During unspecified activity,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W69,2023
1927,Drowning and submersion due to accident to wat...,400,55 - 64 years,Asian,Non-Hispanic Asian (only),male,NaN,Married,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2098,Accidental drowning and submersion while in ba...,409,65 - 74 years,White,Non-Hispanic White (only),male,Home,Married,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W65,2023
2115,Drowning and submersion due to accident on boa...,400,15 - 24 years,White,Non-Hispanic White (only),male,NaN,"Never married, single",During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V925,2023
2120,Drowning and submersion due to accident to wat...,400,25 - 34 years,White,Non-Hispanic White (only),female,Unspecified place,Married,During unspecified activity,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2187,Drowning and submersion due to accident to wat...,400,35 - 44 years,White,Non-Hispanic White (only),female,NaN,Married,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2213,Drowning and submersion due to accident to wat...,400,45 - 54 years,Asian,Non-Hispanic Asian (only),female,NaN,Married,During unspecified activity,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2214,Drowning and submersion due to accident to wat...,400,55 - 64 years,Asian,Non-Hispanic Asian (only),female,NaN,Marital Status unknown,During unspecified activity,Associate degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2215,Drowning and submersion due to accident to wat...,400,25 - 34 years,White,Hispanic origin unknown or not stated,male,NaN,"Never married, single",During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2569,Drowning and submersion due to accident on boa...,400,65 - 74 years,White,Non-Hispanic White (only),male,NaN,Divorced,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V925,2023
2709,Drowning and submersion due to accident to wat...,400,65 - 74 years,White,Non-Hispanic White (only),male,Unspecified place,Married,During unspecified activity,Doctorate or professional degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V909,2023
2767,Accidental drowning and submersion while in ba...,409,65 - 74 years,White,Non-Hispanic White (only),female,Home,Divorced,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W65,2023

In [266]:
#decoding the universal_set
universal_set = universal_set.replace(map_2023)
#checking decode
universal_set.head(20)

,icd,icd_recode,age,race,race_12,sex,location,marital,activity,education,...,co-morb_13,co-morb_14,co-morb_15,co-morb_16,co-morb_17,co-morb_18,co-morb_19,co-morb_20,icd_raw,year
0,C55,108,65 - 74 years,White,Mexican,female,NaN,Married,NaN,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C55,2023
1,J44,267,65 - 74 years,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,female,NaN,Divorced,NaN,Associate degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J441,2023
2,Y34,448,45 - 54 years,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,female,Unspecified place,Divorced,During unspecified activity,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y34,2023
3,I64,238,55 - 64 years,White,Non-Hispanic White (only),male,NaN,Married,NaN,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I64,2023
4,G30,189,85 years and older,White,Non-Hispanic White (only),male,NaN,Divorced,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G309,2023
5,E14,159,85 years and older,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,male,NaN,Divorced,NaN,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E149,2023
6,J10,253,65 - 74 years,White,Non-Hispanic White (only),female,NaN,Married,NaN,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J100,2023
7,K44,291,85 years and older,White,Non-Hispanic White (only),female,NaN,Married,NaN,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K449,2023
8,I11,207,75 - 84 years,White,Non-Hispanic White (only),female,NaN,Divorced,NaN,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I119,2023
9,C25,88,75 - 84 years,American Indian and Alaska Native,Non-Hispanic American Indian and Alaska Native...,female,NaN,Widowed,NaN,"some college credit, but no degree",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C259,2023
10,I73,243,85 years and older,White,Non-Hispanic White (only),female,NaN,Divorced,NaN,Doctorate or professional degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I739,2023
11,F03,175,75 - 84 years,White,Non-Hispanic White (only),female,NaN,Divorced,NaN,high school graduate or GED completed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F03,2023
12,I25,215,85 years and older,White,Non-Hispanic White (only),male,NaN,Widowed,NaN,Master’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I251,2023
13,I10,206,85 years and older,White,Non-Hispanic White (only),female,NaN,Widowed,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I10,2023
14,C34,93,75 - 84 years,White,Mexican,male,NaN,Widowed,NaN,8th grade or less,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C349,2023
15,M62,315,75 - 84 years,White,Non-Hispanic White (only),male,NaN,Widowed,NaN,Master’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M628,2023
16,C25,88,75 - 84 years,White,Non-Hispanic White (only),female,NaN,Widowed,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C259,2023
17,I38,226,85 years and older,White,Non-Hispanic White (only),female,NaN,Married,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I38,2023
18,C71,122,65 - 74 years,White,Non-Hispanic White (only),male,NaN,Married,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C719,2023
19,U07,54,65 - 74 years,White,Non-Hispanic White (only),female,NaN,Married,NaN,Bachelor’s degree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U071,2023

In [267]:
#saving universal set
universal_set.to_csv('universal set 2023.csv')

In [268]:
# saving file to local disk to upload to tableau
drowning_test.to_csv('drowning_deaths_2023.csv')

In [269]:
# calculating race counts with race 12 recode
drowning_counts = drowning_test.value_counts('race_12')
# restting index to convert to frame for more calculations
drowning_counts = drowning_counts.reset_index()
# calculating precent of drowning deaths from each group
drowning_counts['percent'] = drowning_counts['count']/len(drowning_test) * 100

In [270]:
print(drowning_counts)

                                              race_12  count    percent
0                           Non-Hispanic White (only)   2556  57.464029
1                           Non-Hispanic Black (only)    689  15.490108
2                                             Mexican    406   9.127698
3                           Non-Hispanic Asian (only)    228   5.125899
4                                    Central American    156   3.507194
5                     Non-Hispanic more than one race     86   1.933453
6                           Other or Unknown Hispanic     86   1.933453
7   Non-Hispanic American Indian and Alaska Native...     68   1.528777
8                                         Puerto Rico     50   1.124101
9                                      South American     50   1.124101
10                                              Cuban     22   0.494604
11              Hispanic origin unknown or not stated     21   0.472122
12                                          Dominican     18   0.404676
13  Non-Hispanic Native Hawaiian or Other Pacific ...     12   0.269784

In [271]:
# grouping hispanic so my groups matches previous race data
hispanic_sum = drowning_counts[drowning_counts['race_12'].isin(['Mexican', 'Central American', 'Puerto Rico', 'South American', 'Other or Unknown Hispanic', 'Cuban', 'Dominican'])]
print(hispanic_sum.sum())

race_12    MexicanCentral AmericanOther or Unknown Hispan...
count                                                    788
percent                                            17.715827
dtype: object

In [272]:
# adding hispanic group to the frame
new_frame = pd.DataFrame({'race_12':['Hispanic'], 'count': [788], 'percent':[17.715827]})
final_frame = pd.concat([drowning_counts, new_frame], ignore_index = True)
print(final_frame)

                                              race_12  count    percent
0                           Non-Hispanic White (only)   2556  57.464029
1                           Non-Hispanic Black (only)    689  15.490108
2                                             Mexican    406   9.127698
3                           Non-Hispanic Asian (only)    228   5.125899
4                                    Central American    156   3.507194
5                     Non-Hispanic more than one race     86   1.933453
6                           Other or Unknown Hispanic     86   1.933453
7   Non-Hispanic American Indian and Alaska Native...     68   1.528777
8                                         Puerto Rico     50   1.124101
9                                      South American     50   1.124101
10                                              Cuban     22   0.494604
11              Hispanic origin unknown or not stated     21   0.472122
12                                          Dominican     18   0.404676
13  Non-Hispanic Native Hawaiian or Other Pacific ...     12   0.269784
14                                           Hispanic    788  17.715827

In [273]:
# uploading population data from previous project. 
# source for this data has been lost updated and better population data has been provided
pop_stats = pd.read_csv("population statstics.csv")
#checking upload
pop_stats.head(20)

,year,Total,American Indian/\nAlaska Native,Asian,Black,His-\npanic,Pacific Islander,White,Two or more races,Total percent,American Indian/\nAlaska Native percent,Asian percent,Black percent,His-\npanic percent,Pacific Ispercentlander,White percent,Two or more races percent
0,1980,"227,225","1,336","3,665","26,215","14,869",[\2\],"181,140",---,100,0.6,1.6,11.5,6.5,[\2\],79.7,---
1,1990,"249,623","1,793","7,092","29,439","22,573",[\2\],"188,725",---,100,0.7,2.8,11.8,9.0,[\2\],75.6,---
2,1995,"266,278","2,044","9,188","32,500","28,158",[\2\],"194,389",---,100,0.8,3.5,12.2,10.6,[\2\],73.0,---
3,2000,"282,162","2,102","10,469","34,406","35,662",370,"195,702","3,452",100,0.7,3.7,12.2,12.6,0.1,69.4,1.2
4,2005,"295,517","2,186","12,658","36,147","43,024",434,"196,621","4,447",100,0.7,4.3,12.2,14.6,0.1,66.5,1.5
5,2006,"298,380","2,203","13,098","36,521","44,606",448,"196,833","4,671",100,0.7,4.4,12.2,14.9,0.2,66.0,1.6
6,2007,"301,231","2,220","13,527","36,906","46,197",461,"197,011","4,909",100,0.7,4.5,12.3,15.3,0.2,65.4,1.6
7,2008,"304,094","2,237","13,956","37,291","47,794",475,"197,184","5,158",100,0.7,4.6,12.3,15.7,0.2,64.8,1.7
8,2009,"306,772","2,252","14,361","37,657","49,327",488,"197,275","5,411",100,0.7,4.7,12.3,16.1,0.2,64.3,1.8
9,2010,"309,327","2,269","14,766","38,015","50,736",500,"197,393","5,649",100,0.7,4.8,12.3,16.4,0.2,63.8,1.8
10,2011,"311,583","2,288","15,235","38,384","51,825",511,"197,505","5,835",100,0.7,4.9,12.3,16.6,0.2,63.4,1.9
11,2012,"313,878","2,309","15,718","38,763","52,869",523,"197,671","6,024",100,0.7,5.0,12.3,16.8,0.2,63.0,1.9
12,2013,"316,060","2,329","16,213","39,127","53,907",535,"197,733","6,215",100,0.7,5.1,12.4,17.1,0.2,62.6,2
13,2014,"318,386","2,348","16,748","39,501","54,979",546,"197,854","6,411",100,0.7,5.3,12.4,17.3,0.2,62.1,2
14,2015,"320,739","2,366","17,308","39,878","56,118",558,"197,902","6,610",100,0.7,5.4,12.4,17.5,0.2,61.7,2.1
15,2016,"323,072","2,383","17,850","40,245","57,285",570,"197,928","6,810",100,0.7,5.5,12.5,17.7,0.2,61.3,2.1
16,2017,"325,122","2,398","18,348","40,589","58,403",582,"197,798","7,004",100,0.7,5.6,12.5,18.0,0.2,60.8,2.2
17,2018,"326,838","2,410","18,728","40,899","59,469",594,"197,546","7,192",100,0.7,5.7,12.5,18.2,0.2,60.4,2.2
18,2019,"328,330","2,422","19,075","41,192","60,404",604,"197,256","7,376",100,0.7,5.8,12.5,18.4,0.2,60.1,2.2
19,2020,"331,512","2,406","19,579","41,737","61,839",617,"197,704","7,629",100,0.7,5.9,12.6,18.7,0.2,59.6,2.3

In [274]:
#pulling the year I need and checking it
year_2023 = pop_stats[pop_stats['year'] == 2023]
print(year_2023)

    year    Total American Indian/\nAlaska Native   Asian   Black His-\npanic  \
22  2023  334,995                           2,433  20,752  42,367      64,776

   Pacific Islander    White Two or more races  Total percent  \
22              647  195,830             8,189            100

    American Indian/\nAlaska Native percent  Asian percent  Black percent  \
22                                      0.7            6.2           12.6

    His-\npanic percent Pacific Ispercentlander  White percent  \
22                 19.3                     0.2           58.5

   Two or more races percent
22                       2.4

In [275]:
# adding data by hand into other frame
final_frame.loc[0, 'pop_percent'] = 58.5
final_frame.loc[1, 'pop_percent'] = 12.6
final_frame.loc[3, 'pop_percent'] = 6.2
final_frame.loc[5, 'pop_percent'] = 2.4
final_frame.loc[7, 'pop_percent'] = 0.7
final_frame.loc[13, 'pop_percent'] = 0.2
final_frame.loc[14, 'pop_percent'] = 19.3
#checking input
print(final_frame)

                                              race_12  count    percent  \
0                           Non-Hispanic White (only)   2556  57.464029
1                           Non-Hispanic Black (only)    689  15.490108
2                                             Mexican    406   9.127698
3                           Non-Hispanic Asian (only)    228   5.125899
4                                    Central American    156   3.507194
5                     Non-Hispanic more than one race     86   1.933453
6                           Other or Unknown Hispanic     86   1.933453
7   Non-Hispanic American Indian and Alaska Native...     68   1.528777
8                                         Puerto Rico     50   1.124101
9                                      South American     50   1.124101
10                                              Cuban     22   0.494604
11              Hispanic origin unknown or not stated     21   0.472122
12                                          Dominican     18   0.404676
13  Non-Hispanic Native Hawaiian or Other Pacific ...     12   0.269784
14                                           Hispanic    788  17.715827

    pop_percent
0          58.5
1          12.6
2           NaN
3           6.2
4           NaN
5           2.4
6           NaN
7           0.7
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          0.2
14         19.3

In [276]:
#unable to confirm source of previous population data I went back and pulled data directly from the census bureau
#import acs data 
#File name was edited from the zip file for readability link in read me file
acs_pop =pd.read_csv("ACS_hispanic_race_data.csv")
#checking import
acs_pop.head(20)

,Label (Grouping),United States!!Estimate,United States!!Margin of Error
0,Total:,"334,914,896",*****
1,Not Hispanic or Latino:,"269,774,619","±8,849"
2,White alone,"191,347,640","±60,466"
3,Black or African American alone,"39,569,312","±95,079"
4,American Indian and Alaska Native alone,"1,733,272","±16,041"
5,Asian alone,"19,769,752","±44,702"
6,Native Hawaiian and Other Pacific Isla...,"592,077","±19,817"
7,Some other race alone,"1,949,065","±39,660"
8,Two or more races:,"14,813,501","±122,033"
9,Two races including Some other race,"3,297,389","±54,982"
10,Two races excluding Some other rac...,"11,516,112","±109,337"
11,Hispanic or Latino:,"65,140,277","±8,848"
12,White alone,"11,304,012","±116,032"
13,Black or African American alone,"1,050,660","±35,940"
14,American Indian and Alaska Native alone,"1,608,061","±42,871"
15,Asian alone,"282,571","±14,903"
16,Native Hawaiian and Other Pacific Isla...,"70,340","±7,848"
17,Some other race alone,"22,899,316","±147,631"
18,Two or more races:,"27,925,317","±135,711"
19,Two races including Some other race,"25,226,745","±134,424"

In [277]:
#filtering groups to match race recode 12 groups
acs_pop_extract = acs_pop.iloc[[0,2,3,4,5,6,7,8,11]]
#checking filter
acs_pop_extract.head(10)

,Label (Grouping),United States!!Estimate,United States!!Margin of Error
0,Total:,"334,914,896",*****
2,White alone,"191,347,640","±60,466"
3,Black or African American alone,"39,569,312","±95,079"
4,American Indian and Alaska Native alone,"1,733,272","±16,041"
5,Asian alone,"19,769,752","±44,702"
6,Native Hawaiian and Other Pacific Isla...,"592,077","±19,817"
7,Some other race alone,"1,949,065","±39,660"
8,Two or more races:,"14,813,501","±122,033"
11,Hispanic or Latino:,"65,140,277","±8,848"

In [278]:
#renaming columns for ease of use
acs_pop_extract =  acs_pop_extract.rename(columns = {'United States!!Estimate':'population', 'Label (Grouping)': 'race'})
#checking work 
acs_pop_extract.head()

,race,population,United States!!Margin of Error
0,Total:,"334,914,896",*****
2,White alone,"191,347,640","±60,466"
3,Black or African American alone,"39,569,312","±95,079"
4,American Indian and Alaska Native alone,"1,733,272","±16,041"
5,Asian alone,"19,769,752","±44,702"

In [279]:
#removing commas
acs_pop_extract['population'] = acs_pop_extract['population'].str.replace(',', '',)
#checking work
acs_pop_extract.head()

,race,population,United States!!Margin of Error
0,Total:,334914896,*****
2,White alone,191347640,"±60,466"
3,Black or African American alone,39569312,"±95,079"
4,American Indian and Alaska Native alone,1733272,"±16,041"
5,Asian alone,19769752,"±44,702"

In [280]:
#convering pop to int
acs_pop_extract['population'] = acs_pop_extract['population'].astype('int')
#checking work
acs_pop_extract.head()

,race,population,United States!!Margin of Error
0,Total:,334914896,*****
2,White alone,191347640,"±60,466"
3,Black or African American alone,39569312,"±95,079"
4,American Indian and Alaska Native alone,1733272,"±16,041"
5,Asian alone,19769752,"±44,702"

In [281]:
#calculating percent
acs_pop_extract['population percent'] = (acs_pop_extract['population']/334914896) * 100
acs_pop_extract.head(10)

,race,population,United States!!Margin of Error,population percent
0,Total:,334914896,*****,100.000000
2,White alone,191347640,"±60,466",57.133213
3,Black or African American alone,39569312,"±95,079",11.814736
4,American Indian and Alaska Native alone,1733272,"±16,041",0.517526
5,Asian alone,19769752,"±44,702",5.902918
6,Native Hawaiian and Other Pacific Isla...,592077,"±19,817",0.176784
7,Some other race alone,1949065,"±39,660",0.581958
8,Two or more races:,14813501,"±122,033",4.423064
11,Hispanic or Latino:,65140277,"±8,848",19.449800

In [282]:
#checking other frame for format so I can join frames
final_frame.head(20)

,race_12,count,percent,pop_percent
0,Non-Hispanic White (only),2556,57.464029,58.5
1,Non-Hispanic Black (only),689,15.490108,12.6
2,Mexican,406,9.127698,NaN
3,Non-Hispanic Asian (only),228,5.125899,6.2
4,Central American,156,3.507194,NaN
5,Non-Hispanic more than one race,86,1.933453,2.4
6,Other or Unknown Hispanic,86,1.933453,NaN
7,Non-Hispanic American Indian and Alaska Native...,68,1.528777,0.7
8,Puerto Rico,50,1.124101,NaN
9,South American,50,1.124101,NaN
10,Cuban,22,0.494604,NaN
11,Hispanic origin unknown or not stated,21,0.472122,NaN
12,Dominican,18,0.404676,NaN
13,Non-Hispanic Native Hawaiian or Other Pacific ...,12,0.269784,0.2
14,Hispanic,788,17.715827,19.3

In [283]:
#adding in the population percent by hand, could have changed names and used a join but this seemed quicker for only a few rows 
final_frame.loc[0, 'population percent'] = 57.1
final_frame.loc[1, 'population percent'] = 11.8
final_frame.loc[3, 'population percent'] = 5.9
final_frame.loc[5, 'population percent'] = 4.4
final_frame.loc[7, 'population percent'] = 0.5
final_frame.loc[11, 'population percent'] = 0.6
final_frame.loc[13, 'population percent'] = 0.2
final_frame.loc[14, 'population percent'] = 19.4
final_frame.head(20)

,race_12,count,percent,pop_percent,population percent
0,Non-Hispanic White (only),2556,57.464029,58.5,57.1
1,Non-Hispanic Black (only),689,15.490108,12.6,11.8
2,Mexican,406,9.127698,NaN,NaN
3,Non-Hispanic Asian (only),228,5.125899,6.2,5.9
4,Central American,156,3.507194,NaN,NaN
5,Non-Hispanic more than one race,86,1.933453,2.4,4.4
6,Other or Unknown Hispanic,86,1.933453,NaN,NaN
7,Non-Hispanic American Indian and Alaska Native...,68,1.528777,0.7,0.5
8,Puerto Rico,50,1.124101,NaN,NaN
9,South American,50,1.124101,NaN,NaN
10,Cuban,22,0.494604,NaN,NaN
11,Hispanic origin unknown or not stated,21,0.472122,NaN,0.6
12,Dominican,18,0.404676,NaN,NaN
13,Non-Hispanic Native Hawaiian or Other Pacific ...,12,0.269784,0.2,0.2
14,Hispanic,788,17.715827,19.3,19.4

In [284]:
#dropping na for readability
edit_frame = final_frame.dropna(axis=0)
#comparing drowning percentage to population percentage.
print(edit_frame)

                                              race_12  count    percent  \
0                           Non-Hispanic White (only)   2556  57.464029
1                           Non-Hispanic Black (only)    689  15.490108
3                           Non-Hispanic Asian (only)    228   5.125899
5                     Non-Hispanic more than one race     86   1.933453
7   Non-Hispanic American Indian and Alaska Native...     68   1.528777
13  Non-Hispanic Native Hawaiian or Other Pacific ...     12   0.269784
14                                           Hispanic    788  17.715827

    pop_percent  population percent
0          58.5                57.1
1          12.6                11.8
3           6.2                 5.9
5           2.4                 4.4
7           0.7                 0.5
13          0.2                 0.2
14         19.3                19.4

In [285]:
#save data for loading into tableau
edit_frame.to_csv('drowning_deaths_pop_percent.csv')